ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS nomeCompleto VARCHAR(100);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT false;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS verificado BOOLEAN DEFAULT false;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS token VARCHAR(64);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS expiracaoToken TIMESTAMP;
